type Props = { fullscreen: boolean };
function PageLoading({ fullscreen }: Props) {
    const duration = "2s";
    return (
        <div className="loading-wrapper">
            <div className="top-loading-strip" />
            {fullscreen && (
                <div className="placeholder-loader">
                    <svg
                        className="dna-loading"
                        xmlns="http://www.w3.org/2000/svg"
                        xmlnsXlink="http://www.w3.org/1999/xlink"
                        style={{ margin: "auto", background: "transparent", display: "block" }}
                        width="200px"
                        height="200px"
                        viewBox="0 0 100 100"
                        preserveAspectRatio="xMidYMid"
                    >
                        <circle cx="8" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.5s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="0s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.5s"
                            ></animate>
                        </circle>
                        <circle cx="8" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.5s"
                            ></animate>
                        </circle>
                        <circle cx="20" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.75s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.25s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.75s"
                            ></animate>
                        </circle>
                        <circle cx="20" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.25s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.75s"
                            ></animate>
                        </circle>
                        <circle cx="32" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.5s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1s"
                            ></animate>
                        </circle>
                        <circle cx="32" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1s"
                            ></animate>
                        </circle>
                        <circle cx="44" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.25s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-0.75s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.25s"
                            ></animate>
                        </circle>
                        <circle cx="44" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.25s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.25s"
                            ></animate>
                        </circle>
                        <circle cx="56" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                            ></animate>
                        </circle>
                        <circle cx="56" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.5s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                            ></animate>
                        </circle>
                        <circle cx="68" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.25s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                            ></animate>
                        </circle>
                        <circle cx="68" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.75s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.25s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                            ></animate>
                        </circle>
                        <circle cx="80" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.5s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2s"
                            ></animate>
                        </circle>
                        <circle cx="80" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-3s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.5s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2s"
                            ></animate>
                        </circle>
                        <circle cx="92" cy="50" r="3" fill="#008000">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.25s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-1.75s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#008000;#ff0000;#008000"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.25s"
                            ></animate>
                        </circle>
                        <circle cx="92" cy="50" r="3" fill="#fe5200">
                            <animate
                                attributeName="r"
                                keyTimes="0;0.5;1"
                                values="2.4000000000000004;3.5999999999999996;2.4000000000000004"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-3.25s"
                            ></animate>
                            <animate
                                attributeName="cy"
                                keyTimes="0;0.5;1"
                                values="32;68;32"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.75s"
                                keySplines="0.5 0 0.5 1;0.5 0 0.5 1"
                                calcMode="spline"
                            ></animate>
                            <animate
                                attributeName="fill"
                                keyTimes="0;0.5;1"
                                values="#fe5200;#0000ff;#fe5200"
                                dur={duration}
                                repeatCount="indefinite"
                                begin="-2.25s"
                            ></animate>
                        </circle>
                    </svg>
                </div>
            )}
        </div>
    );
}

export default PageLoading;
